// Audited UI selectors; document rendering is deliberately excluded by the controller.
import { motionTransitions } from "../motion/primitives";

const standardDuration = motionTransitions.standard.duration;

export const motionTargets = [
  ".icon-button",
  ".icon-button.danger",
  '.section-heading[draggable="true"]',
  ".add-entry",
  ".rich-toolbar button",
  ".editor-section-nav-trigger svg",
  ".editor-section-nav-trigger",
  '.editor-section-nav-trigger[aria-expanded="true"]',
  ".editor-section-nav-menu",
  ".editor-section-nav-option",
  ".editor-workspace-pane .editor-scroll > .module-card",
  ".editor-workspace-pane .editor-navigation-target-active",
  ".editor-workspace-pane .summary-card .summary-preview",
  ".editor-workspace-pane .module-card .editor-section-number",
  ".rail-item",
  ".template-library-card",
  ".template-library-select",
  ".editor-workspace-pane button",
  ".template-workspace button",
  ".assistant-workspace button",
  ".editor-workspace-pane .entry-form",
  ".editor-workspace-pane .basic-form",
  ".editor-workspace-pane .content-only-editor",
  ".editor-workspace-pane .entry-list",
  ".editor-workspace-pane .add-entry",
  ".editor-pane > .editor-scroll",
  ".editor-pane > .template-workspace",
  '.manager-row[draggable="true"]',
  ".manager-restore",
  ".floating-menu button",
  ".editor-pane .optional-fields button",
  ".editor-pane .rich-toolbar button",
  ".floating-host :is( .manager-row, .layout-choice-grid button, .layout-segmented button, .floating-menu button, .icon-button, .panel-close )",
  ".floating-host .editor-section-nav-option",
  '.floating-host .editor-section-nav-option[aria-selected="true"]',
  ".floating-host .download-extra-option",
  ".floating-host .download-extra-option.danger-text",
  ".editor-pane select",
  ".floating-host select",
  ".version-workspace select",
  ".editor-workspace-pane .entry-card:not(.expanded)",
  ".editor-workspace-pane .module-actions .icon-button",
  ".editor-workspace-pane .entry-card .entry-actions .icon-button",
  ".editor-workspace-pane .module-actions .icon-button.danger",
  ".editor-workspace-pane .entry-card .entry-actions .icon-button.danger",
  ".topbar :is(.toolbar-button, .action-pill, .title-edit-icon)",
  ".topbar .smart-fill-toggle",
  ".topbar .action-pill.export-trigger",
  ".topbar .smart-fill-toggle:not(.active)",
  ".topbar .smart-fill-toggle.active",
  ".topbar .smart-fill-toggle.smart-fill-pulse",
  ".topbar .toolbar-button > svg:last-child",
  ".topbar .export-trigger > svg:last-child",
  ".floating-host",
  ".floating-host button",
  ".topbar button",
  '.editor-workspace-pane .section-heading[draggable="true"]',
  ".editor-workspace-pane .entry-actions .icon-button.secondary-danger",
  ".editor-workspace-pane .entry-expand-affordance",
  ".editor-workspace-pane .entry-card .entry-actions .secondary-danger",
  ".editor-workspace-pane .entry-actions .secondary-danger",
  ".editor-workspace-pane .section-card > .add-entry",
  ".preview-zoom-control button:not(:disabled)",
  ".preview-fullscreen-control",
  ".preview-pagination button:not(:disabled)",
  ".entry-card .entry-actions .danger",
  ".resume-title",
  ".title-edit-icon",
  ".back-block",
  ".toolbar-button",
  ".toolbar-button.open",
  ".toolbar-button.active",
  ".action-pill",
  ".module-heading",
  ".section-heading",
  ".module-actions .icon-button",
  ".optional-fields button",
  ".avatar-upload .avatar-circle",
  ".basic-card .basic-summary",
  ".entry-card",
  ".summary-card .summary-preview",
  ".basic-form",
  ".content-only-editor",
  ".manager-row",
  ".app-shell button",
  ".app-shell input",
  ".app-shell select",
  '.app-shell [role="button"]',
  ".save-state",
  ".entry-form",
  ".summary-card > .rich-editor",
  ".field input",
  ".field select",
  ".manager-row input",
  ".toggle-group button:not(.active)",
  ".toggle-group button",
  ".save-button",
  ".link-dialog",
  ".link-dialog-actions button",
  ".floating-panel",
  ".floating-menu",
  ".panel-close",
  ".floating-menu .danger-text",
  ".dialog-backdrop",
  ".confirm-dialog",
  ".confirm-actions button",
  ".confirm-actions .confirm-danger",
  ".notice-toast",
  ".action-pill.export-trigger",
  ".download-menu .download-option",
  ".export-spinner",
  ".layout-segmented button",
  ".layout-sort-action",
  ".layout-choice-grid button",
  ".layout-choice-grid button.active",
  ".module-actions .icon-button.danger",
  ".workspace-splitter span",
  ".workspace-resizing .workspace-splitter span",
  ".template-library-delete",
  ".spin",
  ".branch-tree-zoom-button:not(:disabled)",
  ".branch-tree-fit-button:not(:disabled)",
  ".branch-tree-zoom-hint",
  ".icon-action.danger:not(:disabled)",
  ".themed-select-menu button",
  '.themed-select-menu button[aria-selected="true"]',
].join(",");
export const hoverTargets = [
  ".icon-button",
  ".icon-button.danger",
  ".add-entry",
  ".rich-toolbar button",
  ".editor-section-nav-trigger",
  ".editor-section-nav-option",
  ".editor-workspace-pane .editor-scroll > .module-card",
  ".editor-workspace-pane .summary-card .summary-preview",
  ".editor-workspace-pane .module-card",
  ".manager-restore",
  ".floating-menu button",
  ".editor-pane .optional-fields button",
  ".editor-pane .rich-toolbar button",
  ".floating-host :is( .manager-row, .layout-choice-grid button, .layout-segmented button, .floating-menu button, .icon-button, .panel-close )",
  ".floating-host .editor-section-nav-option",
  ".floating-host .download-extra-option",
  ".floating-host .download-extra-option.danger-text",
  ".editor-pane select",
  ".floating-host select",
  ".version-workspace select",
  ".editor-workspace-pane .entry-card:not(.expanded)",
  ".editor-workspace-pane .module-actions .icon-button",
  ".editor-workspace-pane .entry-card .entry-actions .icon-button",
  ".editor-workspace-pane .module-actions .icon-button.danger",
  ".editor-workspace-pane .entry-card .entry-actions .icon-button.danger",
  ".topbar :is(.toolbar-button, .action-pill, .title-edit-icon)",
  ".topbar .action-pill.export-trigger",
  ".topbar .smart-fill-toggle:not(.active)",
  ".topbar .smart-fill-toggle.active",
  ".editor-workspace-pane .entry-actions",
  ".editor-workspace-pane .entry-expand-affordance",
  ".editor-workspace-pane .entry-card",
  ".editor-workspace-pane .section-card > .add-entry",
  ".preview-zoom-control button",
  ".preview-fullscreen-control",
  ".preview-pagination button",
  ".entry-card",
  ".resume-title",
  ".title-edit-icon",
  ".back-block",
  ".toolbar-button",
  ".toolbar-button.active",
  ".action-pill",
  ".module-heading",
  ".section-heading",
  ".module-actions .icon-button",
  ".optional-fields button",
  ".avatar-upload",
  ".basic-card",
  ".summary-card",
  ".basic-form",
  ".content-only-editor",
  ".manager-row",
  ".field input",
  ".field select",
  ".manager-row input",
  ".toggle-group button",
  ".save-button",
  ".link-dialog-actions button",
  ".panel-close",
  ".floating-menu .danger-text",
  ".confirm-actions button",
  ".confirm-actions .confirm-danger",
  ".action-pill.export-trigger",
  ".download-menu .download-option",
  ".layout-segmented button",
  ".layout-sort-action",
  ".layout-choice-grid button",
  ".module-actions .icon-button.danger",
  ".workspace-splitter",
  ".template-library-delete",
  ".branch-tree-zoom-button",
  ".branch-tree-fit-button",
  ".branch-tree-zoom-hint",
  ".icon-action.danger",
  ".themed-select-menu button",
].join(",");
export const pressTargets = [
  '.section-heading[draggable="true"]',
  ".rail-item",
  ".editor-workspace-pane button",
  ".template-workspace button",
  '.manager-row[draggable="true"]',
  ".topbar :is(.toolbar-button, .action-pill, .title-edit-icon)",
  ".topbar button",
  '.editor-workspace-pane .section-heading[draggable="true"]',
  ".resume-title",
  ".title-edit-icon",
  ".toolbar-button",
  ".action-pill",
  ".module-heading",
  ".icon-button",
  ".toggle-group button",
  ".optional-fields button",
  ".add-entry",
  ".save-button",
  ".rich-toolbar button",
  ".panel-close",
  ".floating-menu button",
].join(",");
export const enterPresets = {
  "editor-section-menu-in": {
    times: [0, 1],
    keyframes: {
      opacity: ["0", "1"],
      transform: ["translateY(-4px)", "translateY(0)"],
    },
    duration: standardDuration,
  },
  "editor-navigation-pulse": {
    times: [0, 1],
    keyframes: {
      backgroundColor: ["rgba(255, 90, 54, 0.13)", "rgba(255, 90, 54, 0.06)"],
    },
    duration: 1.4,
  },
  "editorial-content-reveal": {
    times: [0, 1],
    keyframes: {
      opacity: ["0", "1"],
      transform: ["translateY(-5px)", "translateY(0)"],
    },
    duration: standardDuration,
  },
  "editorial-page-enter": {
    times: [0, 1],
    keyframes: {
      opacity: ["0", "1"],
    },
    duration: standardDuration,
  },
  "smart-fill-pulse": {
    times: [0, 0.48, 1],
    keyframes: {
      boxShadow: [
        "0 0 0 0 rgba(238, 91, 42, 0.38)",
        "0 0 0 7px rgba(238, 91, 42, 0.1)",
        "0 0 0 0 rgba(238, 91, 42, 0)",
      ],
      borderColor: [null, "#ee5b2a", null],
      color: [null, "#c8441c", null],
      backgroundColor: [null, "#fff1ea", null],
    },
    duration: 0.52,
  },
  "surface-arrive": {
    times: [0, 1],
    keyframes: {
      opacity: ["0", "1"],
      clipPath: ["inset(0 0 8px 0 round 7px)", "inset(0 0 0 0 round 7px)"],
    },
    duration: standardDuration,
  },
  "ui-popover-in": {
    times: [0, 1],
    keyframes: {
      opacity: ["0", "1"],
      transform: ["translateY(-5px) scale(0.985)", "translateY(0) scale(1)"],
    },
    duration: standardDuration,
  },
  "ui-reveal": {
    times: [0, 1],
    keyframes: {
      opacity: ["0", "1"],
      transform: ["translateY(-5px)", "translateY(0)"],
    },
    duration: standardDuration,
  },
  "ui-dialog-in": {
    times: [0, 1],
    keyframes: {
      opacity: ["0", "1"],
      transform: ["translateY(8px) scale(0.97)", "translateY(0) scale(1)"],
    },
    duration: standardDuration,
  },
  "ui-link-dialog-in": {
    times: [0, 1],
    keyframes: {
      opacity: ["0", "1"],
      transform: [
        "translate(-50%, calc(-50% + 8px)) scale(0.97)",
        "translate(-50%, -50%) scale(1)",
      ],
    },
    duration: standardDuration,
  },
  "ui-fade-in": {
    times: [0, 1],
    keyframes: {
      opacity: ["0", "1"],
    },
    duration: standardDuration,
  },
  "ui-toast-in": {
    times: [0, 1],
    keyframes: {
      opacity: ["0", "1"],
      transform: ["translate(-50%, 8px)", "translate(-50%, 0)"],
    },
    duration: standardDuration,
  },
  "toolbar-dropdown-in": {
    times: [0, 1],
    keyframes: {
      opacity: ["0", "1"],
      transform: ["translateY(-5px) scale(0.985)", "translateY(0) scale(1)"],
    },
    duration: standardDuration,
  },
  "export-spin": {
    times: [0, 1],
    keyframes: {
      transform: ["rotate(0deg)", "rotate(360deg)"],
    },
    duration: 0.85,
    repeat: "infinite",
  },
  "template-spin": {
    times: [0, 1],
    keyframes: {
      transform: ["rotate(0deg)", "rotate(360deg)"],
    },
    duration: 0.8,
    repeat: "infinite",
  },
};
